Repository adopted-ember-addons/ember-file-upload, pull requests merged in 2020-03, with the labels that each got.

#294 fix: Remove DisableGPU from Testem
  testem.js
Labels: internal

#322 Renamed `upload` test helper to `selectFiles` and dropped support for legacy import at `app/tests/helpers/upload`
  addon-test-support/index.js
  test-support/helpers/upload.js
  tests/acceptance/upload-test.js
  tests/dummy/app/templates/docs/testing.md
  tests/integration/components/file-upload-test.js
  tests/integration/components/mirage-handler-test.js
Labels: breaking

#321 Reconfigure addon-docs
  README.md
  package.json
  tests/dummy/app/index.html
  tests/dummy/app/router.js
  tests/dummy/config/environment.js
  tests/dummy/mirage/config.js
  yarn.lock
Labels: documentation, internal

#319 drop official support for ie11
  README.md
  tests/dummy/config/targets.js
Labels: breaking

#327 Improve YUIDoc comments and fix build warnings
  addon/mixins/with-files.js
  addon/queue.js
  addon/services/file-queue.js
Labels: documentation

#333 Add edge to build targets for docs app
  tests/dummy/config/targets.js
Labels: bug, documentation

#320 do not pin dependencies
  package.json
  renovate.json
  yarn.lock
Labels: internal
