Repository adopted-ember-addons/ember-file-upload, pull requests merged in 2022-02, with the labels that each got.

#681 UploadFile: Restore `name` setter
  addon/upload-file.ts
  tests/unit/upload-file-test.js
Labels: bug

#664 Clear mirage deprecations
  addon/mirage/index.js
  package.json
  tests/dummy/mirage/config.js
  tests/dummy/mirage/models/photo.js
  tests/dummy/mirage/serializers/application.js
  yarn.lock
Labels: internal, dependencies

#682 `UploadFile.size `always returns 0
  addon/upload-file.ts
  tests/unit/upload-file-test.js
Labels: bug

#684 Exclude miragejs from ember-auto-import
  index.js
  yarn.lock
Labels: bug

#685 Renovate: Ignore Ember type definitions
  renovate.json
Labels: internal

#700 FileUpload: Defer onFileAdd callback
  addon/components/file-upload.ts
  tests/integration/components/file-upload-test.js
Labels: bug

#678 Update FileDropzone API
  docs/validation.md
  ember-file-upload/addon/components/file-dropzone.hbs
  ember-file-upload/addon/components/file-dropzone.js
  ember-file-upload/addon/components/file-dropzone.ts
  ember-file-upload/addon/components/file-upload.ts
  ember-file-upload/addon/queue.ts
  ember-file-upload/addon/system/data-transfer-wrapper.ts
  ember-file-upload/addon/system/data-transfer.js
  ember-file-upload/tests/dummy/app/components/demo-upload.hbs
  ember-file-upload/tests/helpers/file-queue-helper-test.js
  ember-file-upload/tests/integration/components/file-dropzone-test.js
  ember-file-upload/tests/unit/system/data-transfer-test.js
  ember-file-upload/tests/unit/system/data-transfer-wrapper-test.js
Labels: enhancement

#705 Prefix all callbacks with `on`
  ember-file-upload/addon/components/file-dropzone.ts
  ember-file-upload/addon/components/file-upload.hbs
  ember-file-upload/addon/components/file-upload.ts
  ember-file-upload/addon/helpers/file-queue.ts
  ember-file-upload/addon/queue.ts
  ember-file-upload/tests/dummy/app/components/demo-upload.hbs
  ember-file-upload/tests/helpers/file-queue-helper-test.js
  ember-file-upload/tests/integration/queue-listeners-test.js
Labels: breaking

#710 Restore project-wide doc files to repository root
  CONDUCT.md
  CONTRIBUTING.md
  LICENSE.md
Labels: internal

#711 Remove whitespace when rendering FileUpload
  ember-file-upload/addon/components/file-upload.hbs
  ember-file-upload/tests/integration/components/file-upload-test.js
Labels: bug
