Repository adopted-ember-addons/ember-file-upload, pull requests merged in 2022-01, with the labels that each got.

#640 test(upload): updated filesize since chrome 97 reports it differently
  tests/integration/upload-test.js
Labels: internal

#620 Add events to file-queue helper set up TypeScript, drop ember-cli-addon-docs
  .eslintrc.js
  .github/workflows/ci.yml
  addon/components/file-upload.hbs
  addon/components/file-upload.js
  addon/components/file-upload.ts
  addon/file.js
  addon/helpers/file-queue.js
  addon/helpers/file-queue.ts
  addon/mirage/utils.js
  addon/queue.js
  addon/queue.ts
  addon/services/file-queue.js
  addon/services/file-queue.ts
  addon/system/file-reader.d.ts
  addon/system/upload.d.ts
  addon/system/upload.js
  addon/system/uuid.d.ts
  addon/upload-file.ts
  config/ember-try.js
  package.json
  tests/dummy/app/config/environment.d.ts
  tests/dummy/app/router.js
  tests/dummy/app/templates/application.hbs
  tests/dummy/app/templates/docs.hbs
  tests/dummy/app/templates/index.hbs
  tests/helpers/.gitkeep
  tests/helpers/file-queue-helper-test.js
  tests/integration/components/file-upload-test.js
  tests/integration/upload-test.js
  tests/unit/services/file-queue-test.js
  tests/unit/upload-file-test.js
  tsconfig.json
  types/global.d.ts
  yarn.lock
Labels: enhancement, breaking

#645 Drop docs deployment and required dependencies
  .github/workflows/deploy.yml
  README.md
  config/deploy.js
  package.json
  yarn.lock
Labels: internal

#655 Use guidFor in place of uuid
  addon/components/file-upload.ts
  addon/system/uuid.d.ts
  addon/system/uuid.js
  addon/upload-file.ts
  tests/unit/system/uuid-test.js
Labels: internal

#660 Add type definitions from `@ember/destroyable`
  package.json
  yarn.lock
Labels: internal

#654 Bind FileUpload component to the queue with a modifier. Drop `@ember/render-modifiers`
  addon/components/file-upload.hbs
  addon/components/file-upload.ts
  package.json
  tests/integration/queue-listeners-test.js
  yarn.lock
Labels: bug, dependencies
