Repository adopted-ember-addons/ember-file-upload, pull requests merged in 2022-03, with the labels that each got.

#721 Rewrite `docs/` markdown files with v5 API and add a support matrix to README
  README.md
  docs/file-dropzone.md
  docs/file-validation.md
  docs/getting-started.md
  docs/index.md
  docs/integration.md
  docs/recipes.md
  docs/testing.md
  docs/uploading.md
  docs/validation.md
  ember-file-upload/addon/helpers/file-queue.ts
Labels: documentation

#722 Automate dependency upgrades within SemVer range
  renovate.json
Labels: internal

#723 Add Upgrading to v5 guide
  README.md
  docs/upgrade-guide.md
  ember-file-upload/addon/styles/addon.css
  ember-file-upload/addon/system/file-reader.js
  ember-file-upload/tests/dummy/app/components/demo-upload.hbs
  ember-file-upload/tests/dummy/app/styles/app.scss
Labels: documentation

#731 Add `files` and `index` to `filter` callback
  ember-file-upload/addon/components/file-dropzone.ts
  ember-file-upload/addon/queue.ts
Labels: enhancement

#734 Generate new Docfy documentation website
  README.md
  docs/aws.md
  docs/file-dropzone.md
  docs/file-validation.md
  docs/index.md
  docs/testing.md
  docs/upgrade-guide.md
  docs/uploading.md
  ember-file-upload/CHANGELOG.md
  package.json
  website/.docfy-config.js
  website/.editorconfig
  website/.ember-cli
  website/.eslintignore
  website/.eslintrc.js
  website/.github/workflows/ci.yml
  website/.gitignore
  website/.prettierignore
  website/.prettierrc.js
  website/.template-lintrc.js
  website/.watchmanconfig
  website/README.md
  website/app/app.js
  website/app/components/.gitkeep
  website/app/controllers/.gitkeep
  website/app/formats.js
  website/app/helpers/.gitkeep
  website/app/index.html
  website/app/models/.gitkeep
  website/app/router.js
  website/app/routes/.gitkeep
  website/app/routes/application.js
  website/app/styles/app.css
  website/app/templates/application.hbs
  website/app/templates/docs.hbs
  website/app/templates/index.hbs
  website/config/ember-cli-update.json
  website/config/ember-intl.js
  website/config/environment.js
  website/config/optional-features.json
  website/config/targets.js
  website/ember-cli-build.js
  website/package.json
  website/public/robots.txt
  website/testem.js
  website/tests/helpers/.gitkeep
  website/tests/index.html
  website/tests/integration/.gitkeep
  website/tests/test-helper.js
  website/tests/unit/.gitkeep
  website/vendor/.gitkeep
  yarn.lock
Labels: documentation

#740 Add API Reference section to docs site
  docs/api/class/queue.md
  docs/api/class/upload-file.md
  docs/api/component/file-dropzone.md
  docs/api/component/file-upload.md
  docs/api/helper/file-queue.md
  docs/api/service/file-queue.md
  docs/testing.md
  ember-file-upload/addon/components/file-dropzone.ts
  website/.docfy-config.js
  website/app/templates/api.hbs
  website/app/templates/application.hbs
  website/package.json
  yarn.lock
Labels: documentation

#746 Run docs website CI in GitHub Actions
  .github/workflows/ci.yml
  .github/workflows/docs-ci.yml
  website/.github/workflows/ci.yml
Labels: internal

#747 Update test matrix
  .github/workflows/ci.yml
  ember-file-upload/config/ember-try.js
Labels: internal

#748 Point docs links to newly deployed website
  README.md
  ember-file-upload/package.json
Labels: documentation

#752 Add GitHub link and default page title to docs site
  docs/api/component/file-upload.md
  docs/upgrade-guide.md
  package.json
  website/.docfy-config.js
  website/app/index.html
  website/app/templates/application.hbs
  yarn.lock
Labels: documentation

#706 Deprecate `FileUpload` component and `FileDropzone` attribute args
  ember-file-upload/addon/components/file-dropzone.ts
  ember-file-upload/addon/components/file-upload.ts
  ember-file-upload/addon/queue.ts
  ember-file-upload/addon/services/file-queue.ts
  test-app/tests/unit/services/file-queue-test.js
Labels: enhancement

#754 Correct typos in FileDropzone API docs
  docs/api/component/file-dropzone.md
Labels: documentation
