Repository adopted-ember-addons/ember-file-upload, pull requests merged in 2023-01, with the labels that each got.

#898 Update s3 `uploadImage` example
  docs/aws.md
Labels: documentation

#894 Switch to pnpm and restore `@ember/test-helpers` to latest patch
  .github/workflows/ci.yml
  .github/workflows/docs-ci.yml
  CONTRIBUTING.md
  ember-file-upload/package.json
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  test-app/README.md
  test-app/config/ember-cli-update.json
  test-app/config/ember-try.js
  test-app/package.json
  website/.eslintignore
  website/.gitignore
  website/.prettierignore
  website/README.md
  website/package.json
  yarn.lock
Labels: internal

#900 Restore base website package script
  package.json
Labels: internal

#901 Avoid parallel `prepare` script runs
  package.json
Labels: internal

#888 support ember-modifier v4
  ember-file-upload/package.json
  ember-file-upload/src/interfaces.ts
  ember-file-upload/src/queue.ts
  ember-file-upload/src/system/drag-listener-modifier.ts
  pnpm-lock.yaml
Labels: enhancement

#897 Export QueueName type
  ember-file-upload/src/index.ts
Labels: enhancement
