Repository adopted-ember-addons/ember-file-upload, pull requests merged in 2023-11, with the labels that each got.

#1007 Incorrect file loaded reporting
  ember-file-upload/src/system/upload.ts
Labels: bug

#1012 Fix typo parth -> path
  docs/api/class/queue.md
  docs/api/class/upload-file.md
  docs/api/component/file-dropzone.md
  docs/api/helper/file-queue.md
  docs/api/service/file-queue-service.md
Labels: documentation

#1016 Upload progress incorrect in Google Chrome
  ember-file-upload/src/system/upload.ts
  ember-file-upload/src/upload-file.ts
Labels: bug

#1017 Replay progress events in unit tests
  ember-file-upload/src/internal.ts
  ember-file-upload/src/system/upload.ts
  test-app/tests/unit/system/upload-progress-test.ts
Labels: internal

#1018 Upgrade ember-cli to 5.4
  pnpm-lock.yaml
  test-app/.ember-cli
  test-app/.eslintignore
  test-app/.gitignore
  test-app/.prettierignore
  test-app/.watchmanconfig
  test-app/config/ember-cli-update.json
  test-app/config/ember-try.js
  test-app/package.json
  website/.ember-cli
  website/.eslintignore
  website/.gitignore
  website/.prettierignore
  website/.watchmanconfig
  website/config/ember-cli-update.json
  website/package.json
  website/tests/helpers/index.js
Labels: internal

#1021 Add `lengthComputable: false` event to progress unit tests
  test-app/tests/unit/system/upload-progress-test.ts
Labels: internal

#1022 Adjustable upload speed and queue metrics on demo page
  website/app/components/demo-upload.hbs
  website/app/components/demo-upload.js
  website/app/templates/demo.hbs
Labels: documentation

#1023 Use `<template>` tag on docs website
  .gitattributes
  pnpm-lock.yaml
  website/.prettierrc.js
  website/app/components/demo-upload.gjs
  website/app/components/demo-upload.hbs
  website/app/components/demo-upload.js
  website/package.json
Labels: documentation

#1024 Website demo – support HTTP uploads
  website/app/components/demo-upload.gjs
  website/app/components/options-form.gjs
Labels: documentation
