Repository adopted-ember-addons/ember-file-upload, pull requests merged in 2023-12, with the labels that each got.

#1031 Move release-it to the root, add root scripts
  ember-file-upload/package.json
  package.json
  pnpm-lock.yaml
Labels: internal

#1036 Prepare running twice
  package.json
Labels: internal

#1037 Roll typescript back to 5.2 due to errant `///` comments in declarations
  ember-file-upload/package.json
  pnpm-lock.yaml
  test-app/package.json
Labels: bug

#1050 Drop support for Ember 3.25
  .github/workflows/ci.yml
  ember-file-upload/README.md
  test-app/config/ember-try.js
  test-app/tests/helpers/file-queue-helper-test.ts
Labels: breaking

#1048 Setup `ember-template-imports` in test app
  pnpm-lock.yaml
  test-app/.prettierrc.js
  test-app/app/components/demo-upload.gts
  test-app/app/components/demo-upload.hbs
  test-app/app/components/demo-upload.ts
  test-app/package.json
  test-app/tests/helpers/file-queue-helper-test.ts
  test-app/tests/integration/mirage-handler-test.ts
  test-app/tests/integration/upload-test.gts
  test-app/tsconfig.json
  test-app/types/global.d.ts
Labels: internal

#1049 Migrate all tests to "strict mode"
  pnpm-lock.yaml
  test-app/app/helpers/to-string.ts
  test-app/tests/integration/components/file-dropzone-test.gts
  test-app/tests/integration/helpers/file-queue-helper-test.gts
  test-app/tests/integration/mirage-handler-test.gts
  test-app/tests/integration/progress-test.gts
  test-app/tests/integration/queue-listeners-test.gts
  test-app/tests/integration/queue-listeners-test.ts
  test-app/tests/integration/services/file-queue-test.gts
  test-app/tests/unit/system/http-request-test.js
  test-app/tests/unit/system/upload-file-reader-test.js
  test-app/tests/unit/upload-file-test.ts
  test-app/types/global.d.ts
Labels: internal
