Repository adopted-ember-addons/ember-file-upload, pull requests merged in 2023-05, with the labels that each got.

#914 Return `Reponse.error` when status is outside of 200-599 range
  ember-file-upload/src/system/http-request.ts
  test-app/tests/unit/system/http-request-test.js
Labels: bug

#925 Add `onUploadStarted`, `onUploadSucceeded` and `onUploadFailed` to `file-queue` helper
  docs/api/helper/file-queue.md
  docs/uploading.md
  ember-file-upload/src/helpers/file-queue.ts
  ember-file-upload/src/interfaces.ts
  ember-file-upload/src/queue.ts
  ember-file-upload/src/system/upload.ts
  ember-file-upload/src/upload-file.ts
  test-app/tests/helpers/file-queue-helper-test.js
  test-app/tests/unit/services/file-queue-test.js
Labels: enhancement

#917 Move blueprint provided packages to peerDependencies
  ember-file-upload/package.json
  pnpm-lock.yaml
Labels: breaking

#922 Drop support for node 14
  .github/workflows/ci.yml
  .github/workflows/docs-ci.yml
  ember-file-upload/README.md
  ember-file-upload/package.json
  test-app/package.json
  website/package.json
Labels: breaking

#927 Demo upload – flush queue after successful upload
  website/app/components/demo-upload.js
Labels: documentation

#928 Document `peerDependency` requirements for v8
  docs/index.md
  docs/upgrade-guide.md
  ember-file-upload/CHANGELOG.md
Labels: documentation
